blank_issues_enabled: false
contact_links:
  - name: General Q&A / Discussions
    url: https://github.com/TimothySpriegade/SetlisteR/discussions
    about: For general questions and discussions, please use GitHub Discussions instead of opening an issue.
